# Generated by Django 4.2.7 on 2025-11-02 02:02

from django.db import migrations


def add_sample_data(apps, schema_editor):
    """Add sample data for Srihari Developers website"""
    
    # Get model classes
    Project = apps.get_model('core', 'Project')
    CompanyInfo = apps.get_model('core', 'CompanyInfo')
    Testimonial = apps.get_model('core', 'Testimonial')
    
    # Create company info
    CompanyInfo.objects.get_or_create(
        defaults={
            'name': 'Srihari Developers',
            'tagline': 'Building Dreams, Creating Realities',
            'description': 'Leading construction company in Tirupati specializing in residential and commercial projects.',
            'phone': '+91-9014376635',
            'email': 'info@sriharidevelopers.com',
            'address': 'VSM BUILDING, Renigunta Rd, Tirupati, Andhra Pradesh 517501',
            'established_year': 2015,
            'completed_projects': 50,
            'happy_clients': 200,
        }
    )
    
    # Create sample projects
    Project.objects.get_or_create(
        title='Luxury Villa Complex',
        defaults={
            'description': 'Premium residential villas with modern amenities and beautiful architecture.',
            'location': 'Tirupati',
            'area': '2500 sq ft',
            'status': 'completed',
            'featured': True,
            'category': 'residential'
        }
    )
    
    Project.objects.get_or_create(
        title='Commercial Plaza',
        defaults={
            'description': 'Multi-story commercial building with retail spaces and office facilities.',
            'location': 'Renigunta Road, Tirupati',
            'area': '5000 sq ft',
            'status': 'completed',
            'featured': True,
            'category': 'commercial'
        }
    )
    
    Project.objects.get_or_create(
        title='Modern Apartments',
        defaults={
            'description': 'Contemporary apartment complex with all modern facilities and amenities.',
            'location': 'Tirupati',
            'area': '1200 sq ft',
            'status': 'completed',
            'featured': True,
            'category': 'residential'
        }
    )
    
    # Create sample testimonials
    Testimonial.objects.get_or_create(
        client_name='Rajesh Kumar',
        defaults={
            'content': 'Excellent work quality and timely delivery. Highly recommended for construction projects!',
            'rating': 5,
            'is_featured': True,
            'project_type': 'Villa Construction'
        }
    )
    
    Testimonial.objects.get_or_create(
        client_name='Priya Sharma',
        defaults={
            'content': 'Professional team with great attention to detail. Very satisfied with the results.',
            'rating': 5,
            'is_featured': True,
            'project_type': 'Home Renovation'
        }
    )
    
    Testimonial.objects.get_or_create(
        client_name='Venkat Reddy',
        defaults={
            'content': 'Best construction company in Tirupati. Great experience working with them!',
            'rating': 5,
            'is_featured': True,
            'project_type': 'Commercial Building'
        }
    )


def remove_sample_data(apps, schema_editor):
    """Remove sample data if migration is reversed"""
    Project = apps.get_model('core', 'Project')
    CompanyInfo = apps.get_model('core', 'CompanyInfo')
    Testimonial = apps.get_model('core', 'Testimonial')
    
    # Clean up sample data
    Project.objects.filter(title__in=[
        'Luxury Villa Complex', 
        'Commercial Plaza', 
        'Modern Apartments'
    ]).delete()
    
    Testimonial.objects.filter(client_name__in=[
        'Rajesh Kumar', 
        'Priya Sharma', 
        'Venkat Reddy'
    ]).delete()
    
    CompanyInfo.objects.filter(name='Srihari Developers').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_sample_data, remove_sample_data),
    ]
