# Generated by Django 4.2.7 on 2025-11-02 02:02

from django.db import migrations


def add_sample_data(apps, schema_editor):
    """Add sample data for Srihari Developers website"""
    
    # Get model classes
    Project = apps.get_model('core', 'Project')
    CompanyInfo = apps.get_model('core', 'CompanyInfo')
    Testimonial = apps.get_model('core', 'Testimonial')
    
    # Create company info
    CompanyInfo.objects.get_or_create(
        defaults={
            'company_name': 'Srihari Developers',
            'tagline': 'Building Dreams, Creating Realities',
            'description': 'Leading construction company in Tirupati specializing in residential and commercial projects with over 8 years of experience.',
            'phone': '+91-9014376635',
            'email': 'info@sriharidevelopers.com',
            'address': 'VSM BUILDING, Renigunta Rd, Tirupati, Andhra Pradesh 517501',
            'established_year': 2015,
            'instagram_url': 'https://www.instagram.com/srihari_developers_official/',
        }
    )
    
    # Create sample projects
    Project.objects.get_or_create(
        name='Luxury Villa Complex',
        defaults={
            'description': 'Premium residential villas with modern amenities and beautiful architecture.',
            'location': 'Tirupati',
            'status': 'completed',
            'featured': True,
        }
    )
    
    Project.objects.get_or_create(
        name='Commercial Plaza',
        defaults={
            'description': 'Multi-story commercial building with retail spaces and office facilities.',
            'location': 'Renigunta Road, Tirupati',
            'status': 'completed',
            'featured': True,
        }
    )
    
    Project.objects.get_or_create(
        name='Modern Apartments',
        defaults={
            'description': 'Contemporary apartment complex with all modern facilities and amenities.',
            'location': 'Tirupati',
            'status': 'completed',
            'featured': True,
        }
    )
    
    # Create sample testimonials
    Testimonial.objects.get_or_create(
        client_name='Rajesh Kumar',
        defaults={
            'testimonial_text': 'Excellent work quality and timely delivery. Highly recommended for construction projects!',
            'rating': 5,
            'is_featured': True,
            'project_name': 'Villa Construction',
            'client_position': 'Property Owner'
        }
    )
    
    Testimonial.objects.get_or_create(
        client_name='Priya Sharma',
        defaults={
            'testimonial_text': 'Professional team with great attention to detail. Very satisfied with the results.',
            'rating': 5,
            'is_featured': True,
            'project_name': 'Home Renovation',
            'client_position': 'Homeowner'
        }
    )
    
    Testimonial.objects.get_or_create(
        client_name='Venkat Reddy',
        defaults={
            'testimonial_text': 'Best construction company in Tirupati. Great experience working with them!',
            'rating': 5,
            'is_featured': True,
            'project_name': 'Commercial Building',
            'client_position': 'Business Owner'
        }
    )


def remove_sample_data(apps, schema_editor):
    """Remove sample data if migration is reversed"""
    Project = apps.get_model('core', 'Project')
    CompanyInfo = apps.get_model('core', 'CompanyInfo')
    Testimonial = apps.get_model('core', 'Testimonial')
    
    # Clean up sample data
    Project.objects.filter(name__in=[
        'Luxury Villa Complex', 
        'Commercial Plaza', 
        'Modern Apartments'
    ]).delete()
    
    Testimonial.objects.filter(client_name__in=[
        'Rajesh Kumar', 
        'Priya Sharma', 
        'Venkat Reddy'
    ]).delete()
    
    CompanyInfo.objects.filter(company_name='Srihari Developers').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_sample_data, remove_sample_data),
    ]
